http://localhost:3000/users/login


###
POST  http://localhost:4200/api/services/app/Edition/CreateEdition
Content-Type: application/json



{"edition":{"displayName":"123"},"featureValues":[]}


###

POST https://resourcesapi.youxianbianli.com/goodscategory/getSubGoodsMenu
Content-Type: application/json
xcmchid: 9001
xctoken: jaq7+UslbzoDGwOzpDjn/fCs7td26AJCOwOFiiULVKas8mBH1AdLEZB52YFQqCFFvVRN7OkGGes/t5/Ski3siC6tlwm8YGsQmZFvkEiKlJcrhEEx0IvHduPezZ6cA9wvqYi9zGzkU9lNwNj3CLAPwHei1A==
Referer: https://servicewechat.com/wx062c0b1734e359fe/346/page-frame.html
Accept-Encoding: gzip, deflate, br


{"pickup_id":403247,"lg_wh_id":101,"transfer_id":0,"parentId":1000005,"pickupPid":403247,"subCategoryId":0,"catGroup":"1","page_num":3,"page_size":10,"cityId":420100,"areaId":420105}

###
http://localhost:3000/api/sms/page/openPage


###

http://localhost:3000/api/sms/website-rule/getAll


### 新增规则
POST http://localhost:3000/api/sms/website-rule/add
Content-Type: application/json

{
  "phoneInputXpath":"/html/body/div[2]/div/div[2]/div[2]/div[2]/div[1]/div[1]/div[2]/input",
  "sendSmsButtonXpath":"/html/body/div[2]/div/div[2]/div[2]/div[2]/div[1]/div[1]/div[2]/button",
  "type":"form",
  "startUrl":"https://ones.ai/sign_up.html"
}



###
http://localhost:3000/api/sms/sms-task/getTask


###

http://localhost:3000/api/sms/worker/connect