@startuml Abp.Localization
namespace Abp.Localization{
  
!include ./skin/class-skin-green.puml
!include ./class-uml/Abp.Localization/localizable-string.puml
!include ./class-uml/Abp.Localization/i-localizable-string.puml
!include ./class-uml/Abp.Localization/i-localization-manager.puml
!include ./class-uml/Abp.Localization/localization-context.puml
!include ./class-uml/Abp.Localization/i-localization-context.puml
!include ./class-uml/Abp.Localization/localizable-string-extensions.puml
}
namespace Abp.Dependency{
!include ./class-uml/Abp.Dependency/i-singleton-dependency.puml
}

@enduml