export let getAllDto = {
  result: {
    multiTenancy: {
      isEnabled: true,
      ignoreFeatureCheckForHostUsers: false,
      sides: {
        host: 'Host',
        tenant: 'Tenant',
      },
    },
    session: {
      userId: null,
      tenantId: null,
      impersonatorUserId: null,
      impersonatorTenantId: null,
      multiTenancySide: 'Host',
    },
    localization: {
      currentCulture: {
        name: 'zh-Hans',
        displayName: 'zh (Hans)',
      },
      languages: [
        {
          name: 'zh-Hans',
          displayName: '简体中文',
          icon: 'famfamfam-flags cn',
          isDefault: true,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'de',
          displayName: 'Deutsch',
          icon: 'famfamfam-flags de',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'nl',
          displayName: 'Dutch (Nederlands)',
          icon: 'famfamfam-flags nl',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'en',
          displayName: 'English',
          icon: 'famfamfam-flags us',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'en-GB',
          displayName: 'English (UK)',
          icon: 'famfamfam-flags gb',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'es-MX',
          displayName: 'Español (México)',
          icon: 'famfamfam-flags mx',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'es',
          displayName: 'Español (Spanish)',
          icon: 'famfamfam-flags es',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'fr',
          displayName: 'Français',
          icon: 'famfamfam-flags fr',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'it',
          displayName: 'Italiano',
          icon: 'famfamfam-flags it',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'pt-BR',
          displayName: 'Português (Brasil)',
          icon: 'famfamfam-flags br',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'ru',
          displayName: 'Pусский',
          icon: 'famfamfam-flags ru',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'vi',
          displayName: 'Tiếng Việt',
          icon: 'famfamfam-flags vn',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'tr',
          displayName: 'Türkçe',
          icon: 'famfamfam-flags tr',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: false,
        },
        {
          name: 'ar',
          displayName: 'العربية',
          icon: 'famfamfam-flags sa',
          isDefault: false,
          isDisabled: false,
          isRightToLeft: true,
        },
      ],
      currentLanguage: {
        name: 'zh-Hans',
        displayName: '简体中文',
        icon: 'famfamfam-flags cn',
        isDefault: true,
        isDisabled: false,
        isRightToLeft: false,
      },
      sources: [
        {
          name: 'Abp',
          type: 'MultiTenantLocalizationSource',
        },
        {
          name: 'AbpWeb',
          type: 'MultiTenantLocalizationSource',
        },
        {
          name: 'AbpZero',
          type: 'MultiTenantLocalizationSource',
        },
        {
          name: 'eShopLinker',
          type: 'MultiTenantLocalizationSource',
        },
      ],
      values: {
        Abp: {
          AllOfTheseFeaturesMustBeEnabled:
            '未启用所需功能. 必须启用所有这些功能：{0}',
          AllOfThesePermissionsMustBeGranted:
            '您没有权限进行此操作,您需要以下权限：{0}',
          AtLeastOneOfTheseFeaturesMustBeEnabled:
            '未启用所需功能. 必须至少启用其中一个功能：{0}',
          AtLeastOneOfThesePermissionsMustBeGranted:
            '您没有权限进行此操作,您至少需要下列权限的其中一项：{0}',
          CurrentUserDidNotLoginToTheApplication: '当前用户没有登录到系统！',
          DefaultFromSenderDisplayName: '默认发件人名字',
          DefaultFromSenderEmailAddress: '默认发件人邮箱地址',
          DefaultLanguage: '预设语言',
          DomainName: '域名',
          FeatureIsNotEnabled: '功能未启用：{0}',
          MainMenu: '主菜单',
          Password: '密码',
          ReceiveNotifications: '接收通知',
          SmtpHost: 'SMTP主机',
          SmtpPort: 'SMTP端口',
          TimeZone: '时区',
          UseDefaultCredentials: '使用默认验证',
          Username: '用户名',
          UseSSL: '使用SSL',
        },
        AbpWeb: {
          AreYouSure: '你确定吗?',
          Cancel: '取消',
          DefaultError: '发生错误!',
          DefaultError401: '未通过身份验证!',
          DefaultError403: '你没有权限!',
          DefaultError404: '未找到资源!',
          DefaultErrorDetail: '服务器未发送错误的详细信息.',
          DefaultErrorDetail401: '你应该执行身份认证(登陆)后再执行此操作.',
          DefaultErrorDetail403: '你不能执行此操作.',
          DefaultErrorDetail404: '未在服务中找到请求的资源.',
          EntityNotFound: '实体 {0} 不存在,id = {1}!',
          InternalServerError:
            '对不起,在处理您的请求期间,产生了一个服务器内部错误!',
          ValidationError: '您的请求无效!',
          ValidationNarrativeTitle: '在验证过程中发现以下错误.',
          Yes: '确定',
        },
        AbpZero: {
          CanNotDeleteAdminUser: '不能删除默认管理员{0}!',
          CanNotDeleteStaticRole: '不能删除系统预定义角色: {0}',
          CanNotRenameAdminUser: '不能重命名默认管理员的用户名 {0}',
          Email: '邮箱',
          EmailSecurityCodeBody: '您的安全码是: {0}',
          EmailSecurityCodeSubject: '安全码',
          'Identity.ConcurrencyFailure': '乐观并发失败,对象已修改.',
          'Identity.DefaultError': '发生了一个未知的异常错误.',
          'Identity.DuplicateEmail': "邮箱地址 '{0}' 已被占用.",
          'Identity.DuplicateRoleName': "角色名称 '{0}' 已经被使用.",
          'Identity.DuplicateUserName': '名字{0}已被占用.',
          'Identity.InvalidEmail': "邮箱地址 '{0}' 不符合要求.",
          'Identity.InvalidPasswordHasherCompatibilityMode':
            '提供的哈希密码兼容模式无效.',
          'Identity.InvalidPasswordHasherIterationCount':
            '迭代次数必须是一个正整数.',
          'Identity.InvalidRoleName': "角色名称'{0}'无效.",
          'Identity.InvalidToken': '无效的token.',
          'Identity.InvalidUserName':
            '用户名{0}不符合要求, 只能包含字母和数字.',
          'Identity.LoginAlreadyAssociated': '登录的用户已存在.',
          'Identity.PasswordMismatch': '密码错误.',
          'Identity.PasswordRequireDigit': "密码至少要包含一位数字 ('0'-'9').",
          'Identity.PasswordRequireLower':
            "密码至少要包含一位小写字母 ('a'-'z').",
          'Identity.PasswordRequireNonAlphanumeric':
            '密码必须包含一位非字母特殊符号或数字.',
          'Identity.PasswordRequireUpper':
            "密码至少要包含一位大写字母 ('A'-'Z').",
          'Identity.PasswordTooShort': '密码至少要{0}位.',
          'Identity.RoleNotFound': '角色{0}不存在.',
          'Identity.UserAlreadyHasPassword': '用户已设置密码.',
          'Identity.UserAlreadyInRole': '用户已拥有此角色.',
          'Identity.UserLockedOut': '用户被锁定.',
          'Identity.UserLockoutNotEnabled': '对此用户，不能启用锁定.',
          'Identity.UserNameNotFound': '用户 {0} 不存在.',
          'Identity.UserNotInRole': '用户不包含此角色.',
          InvalidFeatureValue: '{0}功能的值无效!',
          InvalidTenancyName: '租户名无效!',
          Ldap_Container: '容器',
          Ldap_ContextType: '上下文类型',
          Ldap_Domain: '域名',
          Ldap_IsEnabled: '启用',
          Ldap_Password: '密码',
          Ldap_UserName: '用户名',
          OrganizationUnitDuplicateDisplayNameWarning:
            '已存在名为 {0} 的组织单位. 无法在同一级别创建相同名称的组织单位.',
          RoleDisplayNameIsAlreadyTaken: '角色显示名称 {0}已被占用.',
          RoleNameIsAlreadyTaken: '角色名{0}已被占用.',
          Sms: '短信',
          SmsSecurityCodeMessage: '您的短信验证码是: {0}',
          TenancyNameIsAlreadyTaken: '租户名{0} 已被占用.',
        },
        eShopLinker: {
          '{0}UserCannotBeDeleted': '{不能删除0}用户.',
          AboutUs: '关于我们',
          'Abp.Organizations.OrganizationUnit': '组织单位',
          'Access to your applications and resources, even when you are offline':
            '即使您处于脱机状态，也可以访问您的应用程序和资源',
          AccountSettings: '账号设置',
          Action: '操作',
          ActionInformations: '操作信息',
          Actions: '操作',
          ActivationMailSentMessage:
            '已向您的邮箱发送了一封邮箱地址验证邮件，请查收.',
          Active: '激活',
          AddedTime: '添加时间',
          AddFriend: '添加朋友',
          AddMember: '添加成员',
          Address: '地址',
          AddRootUnit: '添加根组织',
          AddSubUnit: '添加子组织',
          AddUser: '添加用户',
          AdminEmailAddress: '管理员邮箱',
          Administration: '管理',
          AdminPassword: '管理员密码',
          AdminPasswordRepeat: '管理员密码(核对)',
          AdminRoleCannotRemoveFromAdminUser:
            '管理员角色无法从管理员用户中删除',
          All: '全部',
          AllCachesSuccessfullyCleared: '所有缓存清除成功。',
          AllFunctionalityYouHaveInTheApplication:
            '您在应用程序中拥有的所有功能',
          AllOfThesePermissionsMustBeGranted:
            '未授予所需权限。必须授予以下权限：{0}',
          Allow: '允许',
          AllowTenantsToRegisterThemselves: '允许公司注册到系统。',
          AllowTenantsToRegisterThemselves_Hint:
            '如果您禁用此，创建公司只能在公司管理页，并且需要管理员权限 ',
          AllowToRememberBrowserForTwoFactorLogin:
            '允许记住浏览器。如果您允许，用户可以选择记住浏览器，以跳过在同一个浏览器中的再次两步认证登录。',
          AllowUsersToRegisterThemselves: '允许用户注册.',
          AllowUsersToRegisterThemselves_Hint:
            '如果此项被禁用，只能由管理员通过用户管理页面添加用户.',
          Amount: '金额',
          AnErrorOccurred: '发生了一个错误。请稍后重试。',
          AnHttpErrorOccured: '与服务器通信时出错。',
          Annual: '全年',
          AnnualPrice: '每年价格',
          Appearance: '外观',
          ApplicationAccess: '应用程序访问权限',
          ApplicationLogo: '应用程序Logo',
          Apply: '应用',
          AreYouSure: '您确定吗?',
          AssignToAnotherEdition: '分配到另一个版本',
          AtLeastOneOfThesePermissionsMustBeGranted:
            '未授予所需权限。至少授予以下权限之一：{0}',
          Attach: '连接',
          AuditLogDetail: '审计日志详情',
          AuditLogImpersonatedOperationInfo:
            '注意:此操作是由另一个用户代表该用户.',
          AuditLogs: '审计日志',
          Back: '返回',
          BackToMyAccount: '返回我的账户',
          BaseLanguage: '默认语言',
          BaseValue: '默认值',
          Billing: '账单',
          BlockedUsers: '锁定的用户',
          BlockUser: '锁定用户',
          Blue: '蓝色',
          Browse: '浏览',
          Browser: '浏览器',
          BuyNow: '现在购买',
          Caches: '缓存',
          CachesHeaderInfo: '您可以在本页中清除应用程序缓存。',
          CacheSuccessfullyCleared: '清除缓存成功。',
          Cancel: '取消',
          CanNotChangeAdminUserName: '管理用户，不能修改用户名.',
          CanNotEditOrDeleteDefaultLanguages:
            '不能删除默认语言.只能删除或者修改自己增加的语言. 但可以改变所有语言的文本信息.',
          CanNotUpgradeSubscriptionSinceTenantHasNoEditionAssigned:
            '由于公司没有分配版本，因此无法升级订阅。',
          Captcha_Hint: '输入图片中的验证码:',
          CaptchaCanNotBeEmpty: '验证码不能为空.',
          CascadeImpersonationErrorMessage:
            '不能多次模拟登录,这已经是模拟登录!',
          Change: '修改',
          ChangeDateRange: '更改日期范围',
          ChangeLogs: '更改日志',
          ChangePassword: '修改密码',
          ChangePasswordBeforeLinkToAnAccount: '您必须改变这个帐户的密码!',
          ChangePasswordToLogin: '您必须在登录前更改密码！',
          ChangeProfilePicture: '修改头像',
          ChangeTenant: '修改公司',
          ChangeTexts: '改变文本信息',
          ChangingFeatures: '正在修改特性参数',
          ChangingPermissions: '更改权限',
          ChangingTexts: '正在修改文本信息',
          ChartDateFormat: '%Y/%m/%d',
          Chat: '聊天',
          ChatFeature: '聊天',
          ChatFeatureIsNotEnabledForReceiver: '公司没有启用聊天功能。',
          ChatFeatureIsNotEnabledForSender: '您没有启用聊天功能。',
          ChatIsConnecting: '正在连接聊天...',
          ChatIsNotConnectedWarning: '聊天还没有链接。',
          ChatUserSearch_Hint:
            '\n      填写公司用户的唯一用户名， <br>\n      其它公司的用户为 <strong>[公司名称]\\[用户名称]</strong><br><br>\n      例如: <br>\n      .\\admin -> 宿主管理员 <br>\n      Test\\admin -> Test公司的管理员 <br>\n      admin -> 您的公司管理员\n      ',
          Clear: '清除',
          ClearAll: '全部清除',
          ClearedSuccessfully: '已成功清除',
          ClickHere: '点击这里',
          Client: '客户端',
          ClientIsRequestingYourPermission: '{0}正在请求您的许可',
          Close: '关闭',
          Code: '代码',
          Collapse: '断开',
          ConfirmationMailSentPleaseClickLinkInTheEmail:
            '已往您的{0}邮箱发送了一封邮件，请点击邮件中的链接，验证您的邮箱地址.',
          CouldNotValidateExternalUser: '无法验证外部用户登录',
          CreateAnAccount: '注册',
          CreatedAtByUser: '由<b>{1}</b>创建于<b>{0}</b>',
          CreateNewEdition: '创建新的版本',
          CreateNewLanguage: '创建新的语言',
          CreateNewRole: '添加角色',
          CreateNewTenant: '添加公司',
          CreateNewUser: '添加用户',
          CreatingNewEdition: '创建一个新的版本',
          CreatingNewLanguage: '正在创建新的语言',
          CreatingNewRole: '添加角色',
          CreatingNewTenant: '添加公司',
          CreatingNewUser: '添加用户',
          CreationTime: '创建时间',
          CurrentPassword: '当前密码',
          CurrentTenant: '当前公司',
          CurrentUserDidNotLoginToTheApplication:
            '当前用户没有登录该应用程序！',
          CustomCSS: '自定义CSS',
          CustomData: '自定义数据',
          CustomRange: '自定义范围',
          Daily: '每日',
          Dashboard: '工作台',
          DashboardDemo_Note_Info:
            '\n      在这个演示系统，您可以使用左边的菜单功能，测试和了解以下模块的全部功能：用户管理、角色管理、系统设置。\n      主面板(Dashboard)页面只是用于演示目的，文本和数据没有什么含义(所有数据都是硬编码在浏览器客户端程序；\n      其中的MEMBER ACTIVITY图表，向服务器端请求简单随机数据用于展示，当您点击刷新按钮时，可以看到变化。)\n    ',
          DashboardDemo_Note_Title: '欢迎使用ASP.NET Zero启动项目!',
          DashboardHeaderInfo: '分析与报告',
          DashboardNoteForMpaVersion:
            '\n      查看本示例:基于<strong>多页面应用</strong>版本，基于ASP.NET MVC和<strong>jQuery</strong>.\n      ',
          DashboardNoteForSpaVersion:
            '\n      查看本示例:基于<strong>单页面应用</strong>版本，基于ASP.NET MVC和<strong>AngularJs</strong>.\n      ',
          DashboardSampleStatistics: '样例统计',
          DashboardSampleStatisticsHelpText: '进度',
          DatabaseConnectionString: '数据库连接字符串',
          Date: '日期',
          DateAndTimePickers: '日期和时间选择器',
          DateFormatShort: 'yyyy-MM-dd',
          DateRange: '日期范围',
          DayCount: '天数',
          Days: '天',
          DeactiveTenant: '不活跃的公司',
          Default: '默认',
          'Default (all) API': '默认（所有）API',
          DefaultAccountLockoutDurationAsSeconds: '帐户锁定持续时间（秒）',
          DefaultFromAddress: '默认发送邮箱地址',
          DefaultFromDisplayName: '默认发送人名字',
          DefaultFromSenderDisplayName: '默认显示名称',
          DefaultFromSenderEmailAddress: '默认电子邮件地址',
          DefaultLanguage: '默认语言',
          DefaultRole_Description: '新用户将默认拥有此角色.',
          Delete: '删除',
          DeletingEdition: '正在删除版本',
          DeletingLanguages: '正在删除语言',
          DeletingRole: '删除角色',
          DeletingTenant: '删除公司',
          DeletingUser: '删除用户',
          Demo_SampleChatMessage:
            '您好，这是一个测试消息。请在不同的浏览器中登录和退出来测试聊天功能。',
          DemoPayPalAccount: '演示PayPal帐户',
          DemoUiComponents: '演示UI组件',
          DemoUiComponents_Info:
            '\n      此页面显示了一些可在您的应用程序中使用的UI组件。\n            此页面中的组件实现为全栈（包括服务器端）。\n    ',
          DemoUiComponents_Info_Metronic_Link_Text:
            '检查Metronic主题以获取更多UI组件',
          Detail: '详情',
          DifferentTenantImpersonationErrorMessage: '不能模拟不同公司的用户!',
          DisplayOrder: '显示顺序',
          DomainName: '域名',
          DoNotAllow: '不允许',
          DontYouHaveAnAccount: '还不是系统用户?',
          Download: '下载',
          DownloadAll: '全部下载',
          Duration: '持续时间',
          Edit: '修改',
          EditEdition: '编辑版本',
          EditingEdition: '正在编辑版本',
          EditingLanguage: '正在编辑语言',
          EditingRole: '修改角色',
          EditingTenant: '修改公司',
          EditingUser: '修改用户',
          Edition: '版本',
          EditionDeleteWarningMessage: '您确定要删除版本{0}吗？',
          EditionName: '版本名称',
          EditionProperties: '版本属性列表',
          Editions: '版本列表',
          EditionsHeaderInfo: '管理当前应用的版本和特性参数',
          EditionStatistics: '版本统计',
          EditLanguage: '编辑语言',
          EditRole: '修改角色',
          EditTenant: '修改公司',
          EditText: '编辑文本',
          EditUser: '修改用户',
          Email: '电子邮件',
          EmailActivation: '发送激活邮件',
          EmailActivation_ClickTheLinkBelowToVerifyYourEmail:
            '请点击以下链接确认您的邮箱地址,并激活您的用户账号:',
          EmailActivation_Subject: '激活您的用户账号',
          EmailActivation_SubTitle:
            '系统发送此邮件验证您的邮箱地址,并激活您的用户账号.',
          EmailActivation_Title: '欢迎使用系统.',
          EmailAddress: '邮箱地址',
          EmailConfirm: '邮箱地址验认',
          EmailConfirmationRequiredForLogin: '必须验证邮箱地址后才能登录.',
          EmailSecurityCodeBody: '您的安全代码是：{0}',
          EmailSecurityCodeSubject: '安全代码',
          EmailSmtp: '邮箱 (SMTP)',
          EmptyOnes: '空值',
          Enable: '启用',
          EnableLdapAuthentication: '启用轻量目录访问协议(LDAP)认证.',
          EnableTwoFactorLogin: '启用两步认证登录',
          EnableUserAccountLockingOnFailedLoginAttempts:
            '登录失败后启用用户的帐户锁定',
          Error: '错误!',
          ErrorState: '错误状态',
          Expand: '扩展',
          ExpiringEditionMustBeAFreeEdition: '到期后强制转为免费版',
          ExpiringTenantsHelpText: '有{1}位客户将在{0}天内到期...',
          ExportToExcel: '导出到Excel',
          Extend: '拓展',
          Extend_Edition_Description: '拓展至{0}版本',
          ExtendedEdition: '已拓展到{0}版',
          Failed: '失败',
          FailedSubscriptionTerminations_Email_Body:
            '终止公司{1}的{0}订阅时失败。您可以在系统日志中找到详细的错误消息。',
          FailedSubscriptionTerminations_Email_Subject: '订阅终止失败',
          FailedSubscriptionTerminations_SubTitle: '一些公司的订阅终止失败',
          FailedSubscriptionTerminations_Title: '订阅终止失败',
          Features: '特性参数列表',
          File: '文件',
          File_Empty_Error: '请选择一个文件！',
          File_Invalid_Type_Error: '文件类型无效！',
          File_SizeLimit_Error: '文件大小超出限制！',
          FileUpload: '上传文件',
          FilterByPermission: '按许可搜索',
          FilterByRole: '按角色搜索',
          FilterOrAddUser: '搜索/添加 用户',
          Flag: '标记',
          ForgotPassword: '不记得密码了?',
          FormBasedRegistration: '基于表单身份验证',
          FormIsNotValidMessage: '部分输入信息不符合要求，请检查并改正..',
          Free: '免费',
          FreeEditionsCannotHaveTrialVersions: '免费版本不需要试用版',
          FreeTrial: '免费试用',
          Friends: '朋友',
          FriendshipRequestAccepted: '对方已成为您的朋友',
          FromTenantToHostImpersonationErrorMessage:
            '不能从公司中模拟本地用户!',
          Gateway: '网关',
          General: '基本信息',
          GoogleAuthenticatorIsNotEnabled:
            '您的帐户未启用Google身份验证器。您必须先在您的设置中启用它。',
          GoogleAuthenticatorReferrerLink:
            '不确定这个页面是什么意思？您可能需要检查一下',
          GoToApplication: '登录系统',
          GoToSubscriptionManagement: '现在订阅',
          Green: '绿色',
          HangfireDashboard: 'Hangfire 仪表盘',
          HasError: '出现错误',
          HasOwnDatabase: '使用自己的数据库',
          HideAdvancedFilters: '隐藏高级过滤',
          HomePage: '主页',
          HostDashboardHeaderInfo: '一般统计和最近的活动',
          Image: '图像',
          ImpersonationTokenErrorMessage: '模拟认证无效或过期',
          Income: '收入',
          IncomeStatistics: '收入统计',
          IncomeWithAmount: '收入：{0}',
          IncorrectCaptchaAnswer: '验证码无效.',
          IncorrectImageFormat: '图像格式不正确！',
          InvalidEmailAddress: '邮箱地址无效',
          InvalidEmailConfirmationCode: '邮箱验证已失效',
          InvalidEmailConfirmationCode_Detail:
            '请您务必通过点击邮件中的重置链接进入本页面.如果已经这样做了,还存在问题,请重试一遍邮箱验证操作!',
          InvalidFeaturesWarning: '一个或者多个特性参数值无效',
          InvalidFormMessage: '部分输入信息不符合要求，请检查并改正.',
          InvalidLanguageCode: '无效的语言代码.',
          InvalidPasswordResetCode: '密码重置已失效',
          InvalidPasswordResetCode_Detail:
            '请您务必通过点击邮件中的重置链接进入本页面.如果已经这样做了,还存在问题,请重试一遍密码重置操作!',
          InvalidPhoneNumber: '字段{0}不是有效的电话号码',
          InvalidRegularExpression: '字段{0}无效。',
          InvalidSecurityCode: '无效的安全代码！',
          InvalidUserNameOrEmailAddress: '用户名或Email地址无效',
          InvalidUserNameOrPassword: '用户名或密码无效',
          Invoice: '发票',
          InvoiceInfoIsMissingOrNotCompleted: '发票信息缺失或未完成',
          InvoiceInformation: '发票信息',
          InvoiceNo: '发票号',
          InvoiceTo: '发票给',
          IpAddress: 'IP地址',
          IsDisabled: '已禁用',
          IsEmailVerificationEnabled: '启用电子邮件验证。',
          IsEnabled: '是否已启用',
          IsGoogleAuthenticatorEnabled: '启用Google身份验证器',
          IsInTrialPeriod: '是否在试用期？',
          IsLockoutEnabled: '是否启用锁定？',
          IsLockoutEnabled_Hint:
            '在一定数量的失败登录尝试后，用户将被锁定一段时间。',
          IsSmsVerificationEnabled: '启用短信验证。',
          IsTrialActive: '是否是试用',
          IsTwoFactorEnabled: '是否启用双因素身份验证？',
          Key: '键值',
          Language: '语言',
          LanguageDeleteWarningMessage: '确定要删除当前语言包吗 {0}?',
          Languages: '语言列表',
          LanguagesHeaderInfo: '管理语言包的文本头信息',
          LanguageTexts: '语言的文本信息',
          LanguageTextsHeaderInfo: '编辑语言的文本头信息.',
          Last30Days: '最近30天',
          Last7Days: '最近7天',
          LastLoginTime: '上次登录时间',
          LastModificationTime: '最后修改时间',
          LastMonth: '上个月',
          LatestPaymentAmount: '最后付款金额',
          LdapSettings: 'LDAP设置',
          LeaveEmptyToSwitchToHost: '想要切换到宿主请留空',
          LeftMenu: '左侧菜单',
          LegalName: '法定名称',
          LengthNotInRange: '字段{0}的长度必须介于{1}和{2}之间。',
          LessThanMinStringLength: '字段{0}的最小长度为{1}。',
          Link: '链接',
          LinkedAccounts: '关联账户',
          LinkedUserDeleteWarningMessage: '用户的关联 {0} 将被删除。',
          LinkNewAccount: '创建关联账户',
          LinkToCurrentPage: '链接到当前页面',
          LoadWithThreeDot: '加载中...',
          LogIn: '登录',
          LoginAsThisTenant: '使用这个公司登录',
          LoginAsThisUser: '使用这个用户登录',
          LoginAttempts: '登录记录',
          LoginFailed: '登录失败!',
          LoginForTenants: '公司登录',
          LoginForUsers: '用户登录',
          LoginWith: '登录',
          Logout: '注销',
          LookingForMpaVersion: '查找多页面应用版本号',
          LookingForSpaVersion: '查找单页面应用版本号',
          MailSent: '邮件已发送',
          MainMenu: '主菜单',
          Maintenance: '维护',
          ManageLinkedAccounts: '账户管理',
          ManagingMembers: '管理成员',
          ManagingOrganizationTree: '管理组织机构树',
          MaxFailedAccessAttemptsBeforeLockout:
            '在锁定帐户之前的累计登录失败的最大数量',
          MaximumUserCount: '最大用户数',
          MaximumUserCount_Description: '0 = 无限制',
          MaximumUserCount_Error_Detail: '允许此公司最多拥有{0}名用户。',
          MaximumUserCount_Error_Message: '已达到允许的最大用户数！',
          Members: '组织成员',
          Message: '消息',
          Monthly: '每月',
          MonthlyPrice: '每月价格',
          MySettings: '我',
          Name: '名字',
          NameSurname: '姓名',
          NewChatMessageEmail_Subject: '您有一个新的消息',
          NewChatMessageEmail_SubTitle: '',
          NewChatMessageEmail_Title: '消息详情',
          NewNotifications: '新通知',
          NewOrganizationUnit: '新建组织机构',
          NewPassword: '新密码',
          NewPasswordRepeat: '新密码 (核对)',
          NewRegisteredTenantsIsActiveByDefault: '新注册的默认公司。',
          NewRegisteredTenantsIsActiveByDefault_Hint:
            '如果您禁用这个，新的公司将不启用（和不能登录），直到管理员手动激活帐户。',
          NewRegisteredUsersIsActiveByDefault: '注册用户默认激活.',
          NewRegisteredUsersIsActiveByDefault_Hint:
            '如果此项被禁用，新用户需要通过邮件激活后才能登录.',
          NewSubscriptionAmount: '新订阅金额',
          NewTenant: '新公司',
          NewTenantRegisteredNotificationDefinition: '申请注册的一个新公司。',
          NewTenantRegisteredNotificationMessage:
            '申请注册的新公司。公司的名称: {tenancyName}.',
          NewTenants: '新公司',
          NewUserRegisteredNotificationDefinition: '新用户注册。',
          NewUserRegisteredNotificationMessage:
            '新用户注册成功。用户名:{userName},邮件地址:{emailAddress}。',
          NewValue: '新值',
          Next: '下一步',
          No: '否',
          NoCamera: '找不到可用的相机！',
          NoData: '没有数据',
          NoInternetConnection: '您目前没有连接到互联网',
          None: '没有',
          NoOrganizationUnitDefinedYet: '没有定义组织机构.',
          NoPermission: '您没有任何权限。请联系您的管理员。',
          NotAssigned: '没有分配',
          Note_RefreshPageForPermissionChanges:
            '如果您正在更改自己的权限，则可能需要刷新页面（F5），以在您所做的权限更改生效！',
          Notification: '通知',
          NotificationDeleteWarningMessage: '此通知将被删除',
          Notifications: '通知',
          NotificationSettings: '通知设置',
          NotificationTypes: '通知类型',
          NotImpersonatedLoginErrorMessage: '这不是模拟登录!',
          NotSelected: '未选择',
          Object: '对象',
          Off: '禁用',
          'Offline Access': '离线访问',
          Ok: 'Ok',
          On: '启用',
          OnlyLockedUsers: '仅已锁定用户',
          OopsYouAreLost: '噢! 失踪了.',
          OperationLogs: '操作日志',
          OrganizationTree: '组织结构树',
          OrganizationUnitDeleteWarningMessage: '您确定删除组织机构 {0}?',
          OrganizationUnitMoveConfirmMessage: '请确认移动 {0} 到 {1}.',
          OrganizationUnitNotFoundForThisUser: '此用户没有组织单位。',
          OrganizationUnitsHeaderInfo: '应用组织机构和行政区划到用户和实体',
          OriginalValue: '原始值',
          Others: '其他',
          OtherSettings: '其它设置',
          Pages: '页面',
          Paid: '付费',
          Parameters: '参数',
          Password: '密码',
          PasswordChangeDontRememberMessage: '忘记密码？ {0}.',
          PasswordComplexity: '密码复杂性',
          PasswordComplexity_MaxLength_Hint: '密码不能大于 {0} 个字符',
          PasswordComplexity_MinLength_Hint: '密码必须包含 {0} 个字符',
          PasswordComplexity_RequireDigit: '缺少数字',
          PasswordComplexity_RequireDigit_Hint:
            "密码至少有一个数字（'0'-'9'）。",
          PasswordComplexity_RequiredLength: '长度不足',
          PasswordComplexity_RequiredLength_Hint: '密码至少为{0}个字符。',
          PasswordComplexity_RequireLowercase: '缺少小写字母',
          PasswordComplexity_RequireLowercase_Hint:
            "密码至少有一个小写字母（'a'-'z'）。",
          PasswordComplexity_RequireNonAlphanumeric: '缺少特殊字符',
          PasswordComplexity_RequireNonAlphanumeric_Hint:
            '密码至少包含一个特殊字符。',
          PasswordComplexity_RequireUppercase: '缺少大写字母',
          PasswordComplexity_RequireUppercase_Hint:
            "密码至少有一个大写字母（'A'-'Z'）。",
          PasswordComplexity_UseLowerCaseLetters_Hint:
            '密码必须包含一个小写字母',
          PasswordComplexity_UseNumbers_Hint: '密码必须包含数字',
          PasswordComplexity_UsePunctuations_Hint: '密码必须包含一个特殊字符',
          PasswordComplexity_UseUpperCaseLetters_Hint:
            '密码必须包含一个大写字母',
          PasswordComplexityNotSatisfied: '过于简单的密码。',
          PasswordRepeat: '密码 (核对)',
          PasswordReset: '重置密码',
          PasswordResetEmail_ClickTheLinkBelowToResetYourPassword:
            '请点击以下链接重置密码:',
          PasswordResetEmail_Subject: '重置密码',
          PasswordResetEmail_SubTitle: '进行密码重置.',
          PasswordResetEmail_Title: '重置密码.',
          PasswordResetMailSentMessage:
            '已向您的邮箱发送了一封密码重置邮件，请查收.',
          PasswordsDontMatch: '密码不匹配！',
          Payment: '付款',
          PaymentCouldNotCompleted: '付款无法完成',
          PaymentHistory: '付款历史',
          PaymentId: '付款ID',
          PaymentInfo: '付款信息',
          PaymentMightBeExpiredWarning:
            '您的操作可能会超时，如果您已经付款，请与我们联系。',
          PaymentPeriodType: '付款期限类型',
          PaymentPeriodType_Annual: '每年',
          PaymentPeriodType_Monthly: '每月',
          Period: '日期',
          Permission: '许可',
          Permissions: '权限',
          PerMonth: '每月',
          PersonalInformations: '个人信息',
          PerYear: '每年',
          PhoneNumber: '电话号码',
          PickFromGallery: '从画廊中挑选',
          Pin: 'Pin',
          Pink: '粉色',
          'Platform.MultiTenancy.Tenant': '公司',
          PleaseEnterAtLeastNCharacter: '请输入至少{0}个字符。',
          PleaseEnterLoginInformation: '请输入登录信息',
          PleaseEnterNoMoreThanNCharacter: '请输入不超过{0}个字符。',
          PleaseEnterYourNewPassword: '请输入新密码.',
          PleaseWaitToConfirmYourEmailMessage:
            '正在确认您的电子邮件地址，请稍后...',
          PostedData: '发布数据',
          PostedValue: '发布数值',
          Previous: '向前',
          Pricing: '价格',
          Print: '打印',
          ProcessingWithThreeDot: '处理中...',
          ProcessTime: '处理时间',
          Profile: '个人信息',
          ProfilePicture_Change_Error: '头像修改错误.',
          ProfilePicture_Change_Info: '只能选择{0}mb内的JPG/JPEG/PNG图片.',
          ProfilePicture_Warn_FileType:
            '只能选择1mb内的JPG/JPEG图片，请重新选择头像文件.',
          ProfilePicture_Warn_SizeLimit:
            '只能选择{0}mb内的JPG/JPEG图片，请重新选择头像文件.',
          Property: '属性',
          Purchase: '购买',
          ReceiveNotifications: '接收通知',
          ReceiveNotifications_Definition:
            '这个选项可以用来完全启用/禁用接收通知。',
          ReceiveNotifications_DisableInfo:
            '您完全禁用接收通知,您可以启用它并选择您想收到通知类型。',
          RecentTenants: '最近的公司',
          RecentTenantsHelpText: '最近{0}天内注册了{1}位客户...',
          Refresh: '刷新',
          RegisterFormUserNameInvalidMessage:
            '请不要使用包含用户名的电子邮件地址。',
          RemainingDay: '剩余1天',
          RemainingTime: '生育时间',
          RememberMe: '记住我',
          RememberMyDecision: '记住我的决定',
          RememberThisBrowser: '记住这个浏览器',
          Remove: '删除',
          RemoveUserFromOuWarningMessage:
            '您确定要从组织机构 {1} 中删除成员 {0} ?',
          RequestedFileDoesNotExists: '请求的文件不存在!',
          RequestTimedOut: '您的请求超时，请稍后再试。',
          Required: '必要',
          RequiredField: '{0}个字段是必需的。',
          Reset: '重置',
          ResetCode: '重置代码',
          ResetFeaturesTooltip:
            '重置公司指定的特性参数设置并且保存.当前公司只会拥有已注册版本的特性参数.',
          ResetPermissionsTooltip:
            '重置用户权限后，用户仅拥有所属角色包含的权限，为用户直接指定的权限将取消.',
          ResetSpecialFeatures: '重置特殊的特性参数',
          ResetSpecialPermissions: '重置直接指定权限',
          ResetSuccessfully: '重置成功',
          ResizedProfilePicture_Warn_SizeLimit:
            '，图片大小不能超过{0}KB。请调整图片大小后再试一次。',
          Role: '角色',
          RoleDeleteWarningMessage:
            '角色 {0} 将被删除，拥有此角色的用户将取消此角色.',
          RoleName: '角色名称',
          RoleProperties: '角色属性',
          Roles: '角色',
          RolesHeaderInfo: '使用角色进行权限分组.',
          Root: '根',
          Rotate: '旋转',
          Save: '保存',
          SaveAll: '保存全部',
          SaveAndClose: '保存 & 关闭',
          SaveAndNext: '保存 & 文本',
          SaveAsSystemDefault: '保存为系统默认值',
          SavedSuccessfully: '保存成功.',
          SavingWithThreeDot: '保存中...',
          ScanQrCodeWithYourMobileApp: '使用您的应用程序扫描此QR码',
          Search: '搜索',
          SearchWithThreeDot: '搜索...',
          'SecondShort{0}': '{0} 秒',
          Security: '安全',
          SeeAllNotifications: '看到所有的通知',
          SeeAllRecords: '查看所有记录',
          SeeDemo: '查看示例',
          Select: '选择',
          SelectAnItem: '选择一个项目',
          SelectAnOrganizationUnitToSeeMembers: '选择一个组织成员。',
          SelectAUser: '选择一个用户',
          SelectDate: '选择日期',
          SelectFile: '选择文件',
          SelectTwoFactorProvider: '选择双因素身份验证提供程序',
          SelectUsers: '选择用户',
          SelfUserRegistrationIsDisabledMessage: '您不能注册!',
          SelfUserRegistrationIsDisabledMessage_Detail:
            '注册功能被禁用，请联系您的系统管理员为您建立用户账号.',
          Send: '发送',
          SendActivationEmail: '发送激活邮件.',
          SendEmailActivationLink_Information:
            '系统在几十秒内向您发送一封邮件,用于激活您的用户账号，请接收并点击邮件内容中的激活链接。如果在2分钟内还没收到这封邮件，请重试.',
          Sender: '发送人',
          SendPasswordResetLink_Information:
            '系统在几十秒内向您发送一封密码重置邮件，如果在3分钟内还没收到这封邮件，请重试.',
          SendSecurityCode: '发送安全代码。',
          SendSecurityCode_Information:
            '您必须通过验证才能登录。请选择一个验证类型。根据选定的验证类型发送代码。',
          SendSecurityCodeErrorMessage: '无法发送安全代码！',
          SendTestEmail: '发送测试邮件',
          Service: '服务',
          SetAllAsRead: '设置所有为已读',
          SetAsDefaultLanguage: '设置当前语言为默认语言',
          SetAsRead: '设置为已读',
          SetRandomPassword: '使用随机密码.',
          Settings: '设置',
          SettingsHeaderInfo: '显示和修改程序设置.',
          ShouldChangePasswordOnNextLogin: '下次登录需要修改密码.',
          ShowAdvancedFilters: '显示高级过滤',
          ShowInvoice: '查看发票',
          SignUp: '登录',
          Sms: '短信',
          SmsSecurityCodeMessage: '您的安全代码是：{0}',
          SmsVerificationEnabled: '启用电话号码验证（通过短信）',
          SmsVerificationMessage: '您的验证码：{0}',
          SmtpHost: 'SMTP服务器',
          SmtpPort: 'SMTP端口',
          Source: '选择源',
          Start: '开始',
          StartUsingFree: '开始免费试用',
          Static: '系统',
          StaticRole_Tooltip: '不能删除系统角色.',
          Status: '状态',
          StringLengthDoesntMatch: '字段{0}的最小长度为{1}，最大长度为{2}。',
          Submit: '提交',
          Subscription: '订阅',
          SubscriptionAssignedToAnother_Email_Body:
            '您的平台订阅已于{1}过期。您当前的版本已分配到{0}。',
          SubscriptionEndDate: '订阅结束日期',
          SubscriptionEndDateUtc: '订阅结束日期（Utc）',
          SubscriptionExpire_Email_Body: '您的平台订阅已于{0}过期。',
          SubscriptionExpire_Email_Subject: '您的平台订阅已过期',
          SubscriptionExpire_SubTitle: '此电子邮件将通知您有关订阅到期的通知',
          SubscriptionExpire_Title: '平台订阅到期',
          SubscriptionExpireNotification: '您的订阅将在{0}天后到期。',
          SubscriptionExpiringSoon_Email_Body: '您的平台订阅将在{0}到期。',
          SubscriptionExpiringSoon_Email_Subject: '您的平台订阅到期通知',
          SubscriptionExpiringSoon_SubTitle:
            '此电子邮件将通知您有关订阅到期的通知。',
          SubscriptionExpiringSoon_Title: '平台订阅到期通知',
          SubscriptionExpiringTenants: '订阅到期的公司',
          SubscriptionInformation: '订阅信息',
          SubscriptionPaymentGatewayType_Paypal: 'Paypal',
          SubscriptionPaymentGatewayType_Stripe: 'Stripe',
          SubscriptionPaymentStatus_Cancelled: 'Cancelled',
          SubscriptionPaymentStatus_Completed: '已完成',
          SubscriptionPaymentStatus_Failed: '以失败',
          SubscriptionPaymentStatus_NotPaid: 'Not Paid',
          SubscriptionPaymentStatus_Paid: 'Paid',
          SubscriptionPrice: '订阅价格',
          Subscriptions: '订阅',
          SubscriptionStartDate: '订阅开始日期',
          Success: '成功',
          SuccessfullyAdded: '添加成功',
          SuccessfullyDeleted: '删除成功.',
          SuccessfullyMoved: '移动成功',
          SuccessfullyRegistered: '注册成功',
          SuccessfullyRemoved: '删除成功',
          SuccessfullySaved: '保存成功.',
          SuccessfullyUnlinked: '关联成功',
          Surname: '姓氏',
          SwitchToLinkedAccountTokenErrorMessage: '模拟令牌无效或过期!',
          'SwitchToTenant=': '切换公司帐号',
          TakePhoto: '拍张照片',
          TargetLanguage: '目标语言',
          TargetUserNotFoundProbablyDeleted: '找不到目标用户。他可能已被删除。',
          TargetValue: '目标值',
          'Tax/VatNo': '税务代码',
          TenancyCodeName: '公司编码',
          TenancyName: '公司名称',
          TenantDatabaseConnectionStringChangeWarningMessage:
            '通知：在更改公司的数据库连接字符串之前，应将公司数据库移到新的位置。更改连接字符串并不会移动数据库。',
          TenantDeleteWarningMessage: '公司 {0} 将被删除.',
          TenantEditionIsNotAssigned: '公司版本未分配',
          'TenantIdIsNotActive{0}': '未激活的公司ID：{0}',
          TenantInformations: '公司信息',
          TenantIsNotActive: '公司 {0} 未激活.',
          TenantManagement: '公司管理',
          TenantName: '公司名称',
          TenantName_Regex_Description:
            '公司名称必须由2个以上字母、数字、-、_组成,以字母开头',
          TenantNameCanNotBeEmpty: '公司名不能为空',
          TenantNameOrTenancyCode: '公司名称/公司代码',
          TenantRegistrationLoginInfo: '单击此处登录',
          Tenants: '公司',
          TenantsCannotCreateLanguage: '公司不能创造语言。',
          TenantSelection: '选择公司',
          TenantSelection_Detail: '请选择一个公司',
          TenantsHeaderInfo: '管理公司.',
          TenantSignUp: '注册公司',
          TenantToHostChatFeature: '与宿主聊天',
          TenantToHostChatFeatureIsNotEnabledForReceiver:
            '当前公司没有启用与宿主聊天功能。',
          TenantToHostChatFeatureIsNotEnabledForSender:
            '您没有启用与宿主聊天的功能。',
          TenantToTenantChatFeature: '与其他公司聊天',
          TenantToTenantChatFeatureIsNotEnabledForReceiver:
            '当前公司没有启用与其他公司聊天功能。',
          TenantToTenantChatFeatureIsNotEnabledForSender:
            '您没有启用与其他公司聊天的功能。',
          TestCheckFeature: '测试功能',
          TestCheckFeature2: '测试功能2',
          TestEmail_Body: '这是一个测试邮件。',
          TestEmail_Subject: '测试电子邮件',
          TestEmailSentSuccessfully: '成功发送测试邮件。',
          TestEmailSettingsHeader: '测试邮件设置',
          ThereIsNoLoggedInUser: '未登录的用户。',
          ThereIsNoNotification: '没有通知。',
          ThereIsNoSuchImageFileWithGivenToken: '没有给定令牌的图像',
          'ThereIsNoTenantDefinedWithName{0}': '公司 {0}不存在',
          ThisEditionIsUsedAsAnExpiringEdition:
            '此版本用作其他版本订阅到期后版本。如果你想让这个版本付费，你应该先从其他版本中删除它。',
          ThisFieldIsRequired: '这是必填栏。',
          ThisInvoiceIsNotYours: '这张发票不是你的！',
          ThisLanguageAlreadyExists: '这种语言已经存在!',
          ThisMonth: '这个月',
          ThisWebSiteRootAddress: '网站http根路径',
          ThisWebSiteRootAddress_Hint:
            '示例： http://mydomain.com/ ，用于外部链接本系统，如密码重置链接',
          Time: '时间',
          TimeoutPleaseTryAgain: '操作超时！请再试一次。',
          Timezone: '时区',
          TimeZoneSettingChangedRefreshPageNotification:
            '时区设置改变。单击“确定”按钮刷新页面，并使更改生效。',
          Today: '今天',
          Toggle: '切换',
          TopMenu: '顶部菜单',
          Total: '总计',
          TotalAmount: '总金额',
          TotalRecordsCount: '总计：{0}',
          Trial: '试用',
          TrialDayCount: '试用天数',
          TrialExpireNotification: '您的试用期将在{0}天后到期。',
          TrialSubscriptionNotification: '您正处于{0}版试用期，{1}购买。',
          TryIt: '试试吧',
          TwoFactorLogin: '两步认证登录',
          TwoFactorLoginIsNotSupported: '目前不支持双因素登录！',
          TypeAMessageHere: '请在这里输入消息...',
          UiCustomization_AllowAsideHiding: '允许一边隐藏',
          UiCustomization_AllowAsideMinimizing: '尽量减少',
          UiCustomization_Boxed: 'Boxed',
          UiCustomization_ContentSkin: '内容皮肤',
          UiCustomization_Dark: '黑暗',
          UiCustomization_Default: '默认',
          UiCustomization_DefaultHiddenAside: '默认隐藏在一边',
          UiCustomization_DefaultMinimizedAside: '默认最小化',
          UiCustomization_Desktop: '桌面段',
          UiCustomization_DesktopFixedHeader: '固定标题',
          UiCustomization_Disabled: '已禁用',
          UiCustomization_DisplayHeaderMenu: '显示Header菜单',
          UiCustomization_DisplaySubmenuArrowDesktop: '显示子菜单箭头',
          UiCustomization_DropdownSkin: '下拉皮肤',
          UiCustomization_DropdownSubmenuSkin: '下拉子菜单皮肤',
          UiCustomization_FixedFooter: '固定Footer',
          UiCustomization_FixedMenu: '固定菜单',
          UiCustomization_Fluid: 'Fluid',
          UiCustomization_Footer: 'Footer',
          UiCustomization_Header: '标题栏',
          UiCustomization_HeaderSkin: '皮肤',
          UiCustomization_Hide: '隐藏',
          UiCustomization_Inherit: '继承',
          UiCustomization_Layout: '布局',
          UiCustomization_LayoutType: '布局类型',
          UiCustomization_Left: '左',
          UiCustomization_Light: '明亮',
          UiCustomization_LightGrey: '浅灰色',
          UiCustomization_Menu: '菜单',
          UiCustomization_MenuPosition: '位置',
          UiCustomization_MenuSkin: '菜单皮肤',
          UiCustomization_Mobile: '移动端',
          UiCustomization_MobileFixedHeader: '固定Header',
          UiCustomization_None: '没有',
          UiCustomization_PushFooter: 'Push footer',
          UiCustomization_SpinnerMessage: '微调消息',
          UiCustomization_Theme: '主题',
          UiCustomization_Top: '上',
          UiCustomization_White: '白色',
          UiCustomizationHeaderInfo: '更改UI的外观',
          UnblockUser: '解锁用户',
          'UnknownTenantId{0}': '未知公司ID：{0}',
          Unlimited: '无限',
          UnlimitedTimeSubscription: '无限时间订阅',
          Unlock: '解锁',
          UnlockedTenandAdmin: '已解锁的管理员用户{0}',
          UnlockedTheUser: '解锁用户 {0}',
          Unread: '未读的',
          Upgrade: '升级',
          Upgrade_Edition_Description: '升级至{0}版本',
          UpgradedTo: '已升级到{0}版',
          Upload: '上传',
          UploadCSS_Info: '选择一个不超过1MB的.css样式表文件。',
          UploadedFile: '已上传文件',
          UploadLogo_Info:
            '选择一张像素为139x35且不超过30KB的JPG/JPEG/PNG/GIF的图片文件。',
          UseCaptchaOnRegistration: '用户注册时使用图片验证码(captcha).',
          UseDefaultCredentials: '默认身份验证',
          UseDefaultSettings: '使用默认设置',
          UseHostDatabase: '使用Host数据库',
          'User profile': '用户资料',
          UserAccount: '用户账户',
          UserAccounts: '用户账户',
          UserBlocked: '用户锁定成功。',
          UserDeleteWarningMessage: '用户 {0} 将被删除.',
          UserEmailIsNotConfirmedAndCanNotLogin:
            '您的邮箱未通过验证.请检查您的邮箱地址是否正确,查收邮件并点击邮件内容中的验证链接进行验证和激活.如果没有收到邮件,请点击[邮箱验证],系统会重新发送一封邮件.',
          UserInformations: '用户信息',
          UserIsAlreadyInTheOrganizationUnit: '这个用户已经在组织机构中!',
          UserIsBlocked: '用户已锁定。',
          UserIsNotActiveAndCanNotLogin: '用户 {0} 未激活，不能登录.',
          UserLockedOutMessage: '用户帐户已被锁定。请稍后再试。',
          UserLockOut: '用户锁定',
          UserManagement: '用户管理',
          UserName: '用户名',
          UserNameOrEmail: '用户名或邮箱地址',
          Users: '用户',
          UserSendYouAFriendshipRequest: '{0} 想添加您为朋友。',
          UsersHeaderInfo: '管理用户及权限.',
          UserUnblocked: '用户解锁成功。',
          UseSsl: '使用SSL',
          UseSystemDefaults: '使用系统默认值',
          VerificationCode: '验证码',
          Verify: '验证',
          VerifySecurityCode: '安全代码',
          VerifySecurityCode_Information: '请输入发送给您的验证码。',
          VerifySecurityCodeNotLoggedInErrorMessage:
            '您应该在登录后再验证！可能您的登录已超时。请转到登录页，然后重新尝试。',
          VerifyYourCode: '校验您的验证码',
          VisualSettings: '视觉设置',
          WaitAfterSubscriptionExpireDate: '订阅到期日期后协商',
          WaitingDayAfterExpire: '到期后等待一天',
          Warning: '等待中',
          WebSiteLogs: '网站日志',
          WebSiteLogsHeaderInfo:
            '您可以看到最新的日志，或下载所有日志的压缩文件。',
          WeCanNotFindThePage: '我们无法提供您想要访问的页面.',
          Weekly: '每周',
          WelcomePage_Info:
            '欢迎使用本应用，您可以从左边的菜单启动要使用的功能。如果您没有看到任何菜单，可能是因为您没有获得任何一项授权，您可以联系您的系统管理员获得授权. ',
          WelcomePage_Title: '欢迎!',
          WelcomeToTheApplicationNotificationMessage:
            '欢迎来到我们的应用 !通知系统是用来告诉您事件。您可以选择您想要哪种类型的通知收到通知设置。',
          WhatWillDoneAfterSubscriptionExpiry: '订阅到期后会怎么做',
          WrongSmsVerificationCode: '错误的验证码！',
          Xms: '{0} ms',
          Yellow: '黄色',
          Yes: '是',
          YesDelete: '是, 执行删除!',
          Yesterday: '昨天',
          YouAlreadySentAFriendshipRequestToThisUser: '您已经添加了这个用户。',
          YouCanBackToYourAccount: '点击此返回我的账户.',
          YouCanManageUsersOrganizationUnitsFromOrganizationUnitsPage:
            '您可以从“组织单位”页面管理用户的组织单位。',
          YouCannotBeFriendWithYourself: '您不能邀请自己做朋友',
          YouCanNotDeleteOwnAccount: '您不能删除自己的用户帐户!',
          YouCannotLinkToSameAccount: '您不能链接到相同的帐户!',
          YouCannotRemoveUserRolePermissionsFromAdminRole:
            '您无法从管理角色中删除用户/角色编辑权限',
          YouCannotRemoveUserRolePermissionsFromAdminUser:
            '您无法从管理员中删除用户/角色编辑权限',
          YouDontHaveAnyBlockedFriend:
            '您没有任何被锁定的用户。如果想锁定一个朋友，请从下拉框中选择一个朋友。',
          YouDontHaveAnyFriend:
            '您没有任何朋友。请填写一个用户名到上面的输入框，然后单击“添加朋友”按钮。',
          'Your email address': '您的电子邮件地址',
          'Your phone number': '您的电话号码',
          'Your postal address': '您的联系地址',
          'Your user identifier': '您的用户标识',
          'Your user profile information (first name, last name, etc.)':
            '您的个人资料信息（姓名等）',
          YourAccountIsWaitingToBeActivatedByAdmin:
            '您的用户账号尚未激活，待系统管理员激活后方能登录使用系统.',
          YourCode: '您的验证码',
          YourEmailIsConfirmedMessage: '您的邮箱已通过验证.',
          YourPasswordHasChangedSuccessfully: '密码修改成功.',
          YourPhoneNumberIsNotVerified: '您的电话号码未经过验证',
          YourPhoneNumberIsVerified: '您的电话号码已经过验证',
        },
      },
    },
    features: {
      allFeatures: {
        'App.MaxUserCount': {
          value: '0',
        },
        TestTenantScopeFeature: {
          value: 'false',
        },
        TestEditionScopeFeature: {
          value: 'false',
        },
        'App.TestCheckFeature': {
          value: 'false',
        },
        'App.TestCheckFeature2': {
          value: 'true',
        },
        'App.ChatFeature': {
          value: 'false',
        },
        'App.ChatFeature.TenantToTenant': {
          value: 'false',
        },
        'App.ChatFeature.TenantToHost': {
          value: 'false',
        },
      },
    },
    auth: {
      allPermissions: {
        Pages: 'true',
        'Pages.Transactions': 'true',
        'Pages.Transactions.Create': 'true',
        'Pages.Transactions.Edit': 'true',
        'Pages.Transactions.Delete': 'true',
        'Pages.Deliveries': 'true',
        'Pages.Deliveries.Create': 'true',
        'Pages.Deliveries.Edit': 'true',
        'Pages.Deliveries.Delete': 'true',
        'Pages.Deliveries.Management': 'true',
        'Pages.Orders': 'true',
        'Pages.Orders.Create': 'true',
        'Pages.Orders.Edit': 'true',
        'Pages.Orders.Delete': 'true',
        'Pages.Orders.Provider': 'true',
        'Pages.Orders.Provider.Create': 'true',
        'Pages.Orders.Provider.Edit': 'true',
        'Pages.Orders.Provider.Delete': 'true',
        'Pages.Orders.Purchaser': 'true',
        'Pages.Orders.Purchaser.Create': 'true',
        'Pages.Orders.Purchaser.Edit': 'true',
        'Pages.Orders.Purchaser.Delete': 'true',
        'Pages.Subjects': 'true',
        'Pages.Subjects.Create': 'true',
        'Pages.Subjects.Edit': 'true',
        'Pages.Subjects.Delete': 'true',
        'Pages.Subjects.Provider': 'true',
        'Pages.Subjects.Provider.Create': 'true',
        'Pages.Subjects.Provider.Edit': 'true',
        'Pages.Subjects.Provider.Delete': 'true',
        'Pages.Subjects.Purchaser': 'true',
        'Pages.Subjects.Purchaser.Create': 'true',
        'Pages.Subjects.Purchaser.Edit': 'true',
        'Pages.Subjects.Purchaser.Delete': 'true',
        'Pages.Quotations': 'true',
        'Pages.Quotations.Create': 'true',
        'Pages.Quotations.Edit': 'true',
        'Pages.Quotations.Delete': 'true',
        'Pages.Quotations.Management': 'true',
        'Pages.QuotationLogs': 'true',
        'Pages.QuotationLogs.Create': 'true',
        'Pages.QuotationLogs.Edit': 'true',
        'Pages.QuotationLogs.Delete': 'true',
        'Pages.SubjectMatches': 'true',
        'Pages.SubjectMatches.Create': 'true',
        'Pages.SubjectMatches.Edit': 'true',
        'Pages.SubjectMatches.Delete': 'true',
        'Pages.ProfitLogs': 'true',
        'Pages.ProfitLogs.Create': 'true',
        'Pages.ProfitLogs.Edit': 'true',
        'Pages.ProfitLogs.Delete': 'true',
        'Pages.Profits': 'true',
        'Pages.Profits.Create': 'true',
        'Pages.Profits.Edit': 'true',
        'Pages.Profits.Delete': 'true',
        'Pages.SKU': 'true',
        'Pages.SKU.Create': 'true',
        'Pages.SKU.Edit': 'true',
        'Pages.SKU.Delete': 'true',
        'Pages.SKU.Management': 'true',
        'Pages.Products': 'true',
        'Pages.Products.Create': 'true',
        'Pages.Products.Edit': 'true',
        'Pages.Products.Delete': 'true',
        'Pages.Products.Management': 'true',
        'Pages.BrandCategories': 'true',
        'Pages.BrandCategories.Create': 'true',
        'Pages.BrandCategories.Edit': 'true',
        'Pages.BrandCategories.Delete': 'true',
        'Pages.Categories': 'true',
        'Pages.Categories.Create': 'true',
        'Pages.Categories.Edit': 'true',
        'Pages.Categories.Delete': 'true',
        'Pages.Categories.Management': 'true',
        'Pages.Brands': 'true',
        'Pages.Brands.Create': 'true',
        'Pages.Brands.Edit': 'true',
        'Pages.Brands.Delete': 'true',
        'Pages.Brands.Management': 'true',
        'Pages.DemoUiComponents': 'true',
        'Pages.Regions': 'true',
        'Pages.Regions.Create': 'true',
        'Pages.Regions.Edit': 'true',
        'Pages.Regions.Delete': 'true',
        'Pages.Regions.Management': 'true',
        'Pages.Administration': 'true',
        'Pages.Administration.Roles': 'true',
        'Pages.Administration.Roles.Create': 'true',
        'Pages.Administration.Roles.Edit': 'true',
        'Pages.Administration.Roles.Delete': 'true',
        'Pages.Administration.Users': 'true',
        'Pages.Administration.Users.Create': 'true',
        'Pages.Administration.Users.Edit': 'true',
        'Pages.Administration.Users.Delete': 'true',
        'Pages.Administration.Users.ChangePermissions': 'true',
        'Pages.Administration.Users.Impersonation': 'true',
        'Pages.Administration.Users.Unlock': 'true',
        'Pages.Administration.Languages': 'true',
        'Pages.Administration.Languages.Create': 'true',
        'Pages.Administration.Languages.Edit': 'true',
        'Pages.Administration.Languages.Delete': 'true',
        'Pages.Administration.Languages.ChangeTexts': 'true',
        'Pages.Administration.AuditLogs': 'true',
        'Pages.Administration.OrganizationUnits': 'true',
        'Pages.Administration.OrganizationUnits.ManageOrganizationTree': 'true',
        'Pages.Administration.OrganizationUnits.ManageMembers': 'true',
        'Pages.Administration.OrganizationUnits.ManageRoles': 'true',
        'Pages.Administration.UiCustomization': 'true',
        'Pages.Administration.Tenant.Settings': 'true',
        'Pages.Administration.Tenant.SubscriptionManagement': 'true',
        'Pages.Administration.Host.Settings': 'true',
        'Pages.Administration.Host.Maintenance': 'true',
        'Pages.Administration.HangfireDashboard': 'true',
        'Pages.Administration.Host.Dashboard': 'true',
        'Pages.Tenant.Dashboard': 'true',
        'Pages.Editions': 'true',
        'Pages.Editions.Create': 'true',
        'Pages.Editions.Edit': 'true',
        'Pages.Editions.Delete': 'true',
        'Pages.Editions.MoveTenantsToAnotherEdition': 'true',
        'Pages.Tenants': 'true',
        'Pages.Tenants.Create': 'true',
        'Pages.Tenants.Edit': 'true',
        'Pages.Tenants.ChangeFeatures': 'true',
        'Pages.Tenants.Delete': 'true',
        'Pages.Tenants.Impersonation': 'true',
      },
      grantedPermissions: {},
    },
    nav: {
      menus: {
        MainMenu: {
          name: 'MainMenu',
          displayName: '主菜单',
          customData: null,
          items: [],
        },
      },
    },
    setting: {
      values: {
        'Abp.Localization.DefaultLanguageName': 'zh-Hans',
        'Abp.Notifications.ReceiveNotifications': 'true',
        'Abp.Timing.TimeZone': 'UTC',
        'Abp.Zero.UserManagement.IsEmailConfirmationRequiredForLogin': 'false',
        'Abp.Zero.OrganizationUnits.MaxUserMembershipCount': '2147483647',
        'Abp.Zero.UserManagement.TwoFactorLogin.IsEnabled': 'false',
        'Abp.Zero.UserManagement.TwoFactorLogin.IsRememberBrowserEnabled':
          'true',
        'Abp.Zero.UserManagement.TwoFactorLogin.IsEmailProviderEnabled': 'true',
        'Abp.Zero.UserManagement.TwoFactorLogin.IsSmsProviderEnabled': 'true',
        'Abp.Zero.UserManagement.UserLockOut.IsEnabled': 'true',
        'Abp.Zero.UserManagement.UserLockOut.MaxFailedAccessAttemptsBeforeLockout':
          '5',
        'Abp.Zero.UserManagement.UserLockOut.DefaultAccountLockoutSeconds':
          '300',
        'Abp.Zero.UserManagement.PasswordComplexity.RequireDigit': 'False',
        'Abp.Zero.UserManagement.PasswordComplexity.RequireLowercase': 'False',
        'Abp.Zero.UserManagement.PasswordComplexity.RequireNonAlphanumeric':
          'False',
        'Abp.Zero.UserManagement.PasswordComplexity.RequireUppercase': 'False',
        'Abp.Zero.UserManagement.PasswordComplexity.RequiredLength': '3',
        'App.TenantManagement.AllowSelfRegistration': 'true',
        'App.TenantManagement.UseCaptchaOnRegistration': 'true',
        'App.UserManagement.SmsVerificationEnabled': 'false',
        'App.TenantManagement.SubscriptionExpireNotifyDayCount': '7',
        'Recaptcha.SiteKey': '',
        'App.UiManagement.Theme': 'default',
        'App.Ordering.DefaultProfit': '0',
        'App.UserManagement.AllowSelfRegistration': 'true',
        'App.UserManagement.UseCaptchaOnRegistration': 'true',
        'App.UserManagement.TwoFactorLogin.IsGoogleAuthenticatorEnabled':
          'false',
        'App.UserManagement.IsCookieConsentEnabled': 'false',
        'App.UserManagement.IsQuickThemeSelectEnabled': 'false',
        'App.UserManagement.UseCaptchaOnLogin': 'false',
        'App.UserManagement.SessionTimeOut.IsEnabled': 'false',
        'App.UserManagement.SessionTimeOut.TimeOutSecond': '30',
        'App.UserManagement.SessionTimeOut.ShowTimeOutNotificationSecond': '30',
        'App.UserManagement.AllowOneConcurrentLoginPerUser': 'False',
        'default.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'default.App.UiManagement.Header.MobileFixedHeader': 'false',
        'default.App.UiManagement.Header.Skin': 'light',
        'default.App.UiManagement.SubHeader.Fixed': 'true',
        'default.App.UiManagement.SubHeader.Style': 'solid',
        'default.App.UiManagement.Left.AsideSkin': 'light',
        'default.App.UiManagement.Left.FixedAside': 'true',
        'default.App.UiManagement.Left.AllowAsideMinimizing': 'true',
        'default.App.UiManagement.Left.DefaultMinimizedAside': 'false',
        'default.App.UiManagement.Left.SubmenuToggle': 'false',
        'default.App.UiManagement.Footer.FixedFooter': 'false',
        'default.App.UiManagement.MenuSearch': 'false',
        'theme2.App.UiManagement.LayoutType': 'fixed',
        'theme2.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme2.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme2.App.UiManagement.Header.MinimizeType': 'topbar',
        'theme2.App.UiManagement.Header.MenuArrows': 'true',
        'theme2.App.UiManagement.MenuSearch': 'false',
        'theme3.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme3.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme3.App.UiManagement.SubHeader.Fixed': 'true',
        'theme3.App.UiManagement.SubHeader.Style': 'solid',
        'theme3.App.UiManagement.Footer.FixedFooter': 'false',
        'theme3.App.UiManagement.MenuSearch': 'false',
        'theme4.App.UiManagement.LayoutType': 'fixed',
        'theme4.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme4.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme4.App.UiManagement.Header.MinimizeType': 'menu',
        'theme4.App.UiManagement.Header.MenuArrows': 'true',
        'theme4.App.UiManagement.MenuSearch': 'false',
        'theme5.App.UiManagement.LayoutType': 'fixed',
        'theme5.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme5.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme5.App.UiManagement.Header.MinimizeType': 'menu',
        'theme5.App.UiManagement.Header.MenuArrows': 'true',
        'theme5.App.UiManagement.Footer.FixedFooter': 'false',
        'theme5.App.UiManagement.MenuSearch': 'false',
        'theme6.App.UiManagement.Header.DesktopFixedHeader': 'false',
        'theme6.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme6.App.UiManagement.SubHeader.Fixed': 'false',
        'theme6.App.UiManagement.SubHeader.Style': 'solid',
        'theme6.App.UiManagement.Footer.FixedFooter': 'false',
        'theme6.App.UiManagement.MenuSearch': 'false',
        'theme7.App.UiManagement.Header.DesktopFixedHeader': 'false',
        'theme7.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme7.App.UiManagement.SubHeader.Fixed': 'false',
        'theme7.App.UiManagement.SubHeader.Style': 'solid',
        'theme7.App.UiManagement.Footer.FixedFooter': 'false',
        'theme7.App.UiManagement.MenuSearch': 'false',
        'theme8.App.UiManagement.LayoutType': 'fluid',
        'theme8.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme8.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme8.App.UiManagement.MenuSearch': 'false',
        'theme9.App.UiManagement.LayoutType': 'fixed',
        'theme9.App.UiManagement.Header.DesktopFixedHeader': 'false',
        'theme9.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme9.App.UiManagement.MenuSearch': 'true',
        'theme10.App.UiManagement.LayoutType': 'fixed',
        'theme10.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme10.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme10.App.UiManagement.MenuSearch': 'false',
        'theme11.App.UiManagement.LayoutType': 'fluid',
        'theme11.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme11.App.UiManagement.Left.FixedAside': 'true',
        'theme11.App.UiManagement.MenuSearch': 'false',
        'theme12.App.UiManagement.Header.DesktopFixedHeader': 'true',
        'theme12.App.UiManagement.Header.MobileFixedHeader': 'false',
        'theme12.App.UiManagement.SubHeader.Fixed': 'false',
        'theme12.App.UiManagement.SubHeader.Style': 'solid',
        'theme12.App.UiManagement.Left.FixedAside': 'true',
        'theme12.App.UiManagement.Left.SubmenuToggle': 'false',
        'theme12.App.UiManagement.Footer.FixedFooter': 'false',
        'theme12.App.UiManagement.MenuSearch': 'false',
        'App.DashboardCustomization.Configuration.Mvc':
          '[{"DashboardName":"TenantDashboard","Pages":[{"Id":"Page8bbe95deed4042e1bae2473ee2e63b82","Name":"Default Page","Widgets":[{"WidgetId":"Widgets_Tenant_GeneralStats","Height":9,"Width":6,"PositionX":0,"PositionY":19},{"WidgetId":"Widgets_Tenant_ProfitShare","Height":13,"Width":6,"PositionX":0,"PositionY":28},{"WidgetId":"Widgets_Tenant_MemberActivity","Height":13,"Width":6,"PositionX":6,"PositionY":28},{"WidgetId":"Widgets_Tenant_RegionalStats","Height":14,"Width":6,"PositionX":6,"PositionY":5},{"WidgetId":"Widgets_Tenant_DailySales","Height":9,"Width":6,"PositionX":6,"PositionY":19},{"WidgetId":"Widgets_Tenant_TopStats","Height":5,"Width":12,"PositionX":0,"PositionY":0},{"WidgetId":"Widgets_Tenant_SalesSummary","Height":14,"Width":6,"PositionX":0,"PositionY":5}]}]},{"DashboardName":"HostDashboard","Pages":[{"Id":"Page96972978b4a84e1c8974d4349dace712","Name":"Default Page","Widgets":[{"WidgetId":"Widgets_Host_TopStats","Height":6,"Width":12,"PositionX":0,"PositionY":0},{"WidgetId":"Widgets_Host_IncomeStatistics","Height":11,"Width":7,"PositionX":0,"PositionY":6},{"WidgetId":"Widgets_Host_RecentTenants","Height":10,"Width":5,"PositionX":7,"PositionY":17},{"WidgetId":"Widgets_Host_SubscriptionExpiringTenants","Height":10,"Width":7,"PositionX":0,"PositionY":17},{"WidgetId":"Widgets_Host_EditionStatistics","Height":11,"Width":5,"PositionX":7,"PositionY":6}]}]}]',
        'App.DashboardCustomization.Configuration.Angular':
          '[{"DashboardName":"TenantDashboard","Pages":[{"Id":"Page856f5ad3a8f64d46ba78be608a35e9b7","Name":"Default Page","Widgets":[{"WidgetId":"Widgets_Tenant_TopStats","Height":4,"Width":12,"PositionX":0,"PositionY":0},{"WidgetId":"Widgets_Tenant_SalesSummary","Height":12,"Width":6,"PositionX":0,"PositionY":4},{"WidgetId":"Widgets_Tenant_RegionalStats","Height":12,"Width":6,"PositionX":6,"PositionY":4},{"WidgetId":"Widgets_Tenant_GeneralStats","Height":8,"Width":6,"PositionX":0,"PositionY":16},{"WidgetId":"Widgets_Tenant_DailySales","Height":8,"Width":6,"PositionX":6,"PositionY":16},{"WidgetId":"Widgets_Tenant_ProfitShare","Height":11,"Width":6,"PositionX":0,"PositionY":24},{"WidgetId":"Widgets_Tenant_MemberActivity","Height":11,"Width":6,"PositionX":6,"PositionY":24}]}]},{"DashboardName":"HostDashboard","Pages":[{"Id":"Pageeeab5656c469434db63189de2dfa5b80","Name":"Default Page","Widgets":[{"WidgetId":"Widgets_Host_TopStats","Height":4,"Width":12,"PositionX":0,"PositionY":0},{"WidgetId":"Widgets_Host_IncomeStatistics","Height":8,"Width":7,"PositionX":0,"PositionY":4},{"WidgetId":"Widgets_Host_RecentTenants","Height":9,"Width":5,"PositionX":7,"PositionY":12},{"WidgetId":"Widgets_Host_SubscriptionExpiringTenants","Height":9,"Width":7,"PositionX":0,"PositionY":12},{"WidgetId":"Widgets_Host_EditionStatistics","Height":8,"Width":5,"PositionX":7,"PositionY":4}]}]}]',
      },
    },
    clock: {
      provider: 'unspecifiedClockProvider',
    },
    timing: {
      timeZoneInfo: {
        windows: {
          timeZoneId: 'UTC',
          baseUtcOffsetInMilliseconds: 0.0,
          currentUtcOffsetInMilliseconds: 0.0,
          isDaylightSavingTimeNow: false,
        },
        iana: {
          timeZoneId: 'Etc/UTC',
        },
      },
    },
    security: {
      antiForgery: {
        tokenCookieName: 'XSRF-TOKEN',
        tokenHeaderName: 'X-XSRF-TOKEN',
      },
    },
    custom: {},
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true,
};
