@startuml LocalizationContext

class LocalizationContext  implements Abp.Dependency.ISingletonDependency,ILocalizationContext
    {
        public ILocalizationManager LocalizationManager { get; }
       
        public LocalizationContext(ILocalizationManager localizationManager)
      
    }
@enduml